print("B. Write a Python program to remove an item from a set if it is present in the set.")
print("D21CE180 - SHREYASH CHAUHAN")
num_set = set([0, 1, 2, 3, 4, 5])
print("ORIGINAL SET ELEMENTS :", num_set)
num_set.discard(0)
print("REMOVE 0 FROM THE SET : ", num_set)
num_set.discard(4)
print("REMOVE 4 FROM THE SET : ", num_set)
num_set.discard(2)
print("REMOVE 2 FROM THE SET : ", num_set)

