print("C. Write a Python program to add an item in a tuple.")
print("D21CE180 - SHREYASH CHAUHAN")
t = (1, 2, 3, 4, 5)
print("BEFORE ADDING ITEM =", t)
v = list(t)
v.append(6)
t = tuple(v)
print("AFTER ADDING ITEM =", t)
