print("A. Write a Python program to add member(s) in a set and clear a set")
print("D21CE180 - SHREYASH CHAUHAN")
color_set = set()
print("COLOR SET :", color_set)
print("ADD SINGLE ELEMENT : Red")
color_set.add("Red")
print("ADD MULTIPLE ELEMENTS : Blue, green")
color_set.update(["Blue", "Green"])
print("ALL ELEMENTS :", color_set)
color_set.clear()
print("AFTER CLEAR :", color_set)

